#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-pymdown_extensions
Version  : 9.3
Release  : 3
URL      : https://files.pythonhosted.org/packages/d2/1f/b1b7f5b03b3c42d9a68eb843ff22047aa87dbe8a8b8991c4b1574b29c9be/pymdown-extensions-9.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/d2/1f/b1b7f5b03b3c42d9a68eb843ff22047aa87dbe8a8b8991c4b1574b29c9be/pymdown-extensions-9.3.tar.gz
Summary  : Extension pack for Python Markdown.
Group    : Development/Tools
License  : MIT
Requires: pypi-pymdown_extensions-license = %{version}-%{release}
Requires: pypi-pymdown_extensions-python = %{version}-%{release}
Requires: pypi-pymdown_extensions-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(markdown)
BuildRequires : pypi(py)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
[![Donate via PayPal][donate-image]][donate-link]
[![Discord][discord-image]][discord-link]
[![Build][github-ci-image]][github-ci-link]
[![Coverage Status][codecov-image]][codecov-link]
[![PyPI Version][pypi-image]][pypi-link]
[![PyPI - Python Version][python-image]][pypi-link]
![License][license-image-mit]

%package license
Summary: license components for the pypi-pymdown_extensions package.
Group: Default

%description license
license components for the pypi-pymdown_extensions package.


%package python
Summary: python components for the pypi-pymdown_extensions package.
Group: Default
Requires: pypi-pymdown_extensions-python3 = %{version}-%{release}

%description python
python components for the pypi-pymdown_extensions package.


%package python3
Summary: python3 components for the pypi-pymdown_extensions package.
Group: Default
Requires: python3-core
Provides: pypi(pymdown_extensions)
Requires: pypi(markdown)

%description python3
python3 components for the pypi-pymdown_extensions package.


%prep
%setup -q -n pymdown-extensions-9.3
cd %{_builddir}/pymdown-extensions-9.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1647712945
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pymdown_extensions
cp %{_builddir}/pymdown-extensions-9.3/LICENSE.md %{buildroot}/usr/share/package-licenses/pypi-pymdown_extensions/180c430e3fd136e9490d747d67cf1a00456e0d1a
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pymdown_extensions/180c430e3fd136e9490d747d67cf1a00456e0d1a

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
