#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-pymdown_extensions
Version  : 9.2
Release  : 2
URL      : https://files.pythonhosted.org/packages/e8/d8/5497fc0f55f87db787e1f61b10390b18247ace5ccd1bf90fef82a6eb628a/pymdown-extensions-9.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/e8/d8/5497fc0f55f87db787e1f61b10390b18247ace5ccd1bf90fef82a6eb628a/pymdown-extensions-9.2.tar.gz
Summary  : Extension pack for Python Markdown.
Group    : Development/Tools
License  : MIT
Requires: pypi-pymdown_extensions-python = %{version}-%{release}
Requires: pypi-pymdown_extensions-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(markdown)
BuildRequires : pypi(py)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
[![Donate via PayPal][donate-image]][donate-link]
[![Discord][discord-image]][discord-link]
[![Build][github-ci-image]][github-ci-link]
[![Coverage Status][codecov-image]][codecov-link]
[![PyPI Version][pypi-image]][pypi-link]
[![PyPI - Python Version][python-image]][pypi-link]
![License][license-image-mit]

%package python
Summary: python components for the pypi-pymdown_extensions package.
Group: Default
Requires: pypi-pymdown_extensions-python3 = %{version}-%{release}

%description python
python components for the pypi-pymdown_extensions package.


%package python3
Summary: python3 components for the pypi-pymdown_extensions package.
Group: Default
Requires: python3-core
Provides: pypi(pymdown_extensions)
Requires: pypi(markdown)

%description python3
python3 components for the pypi-pymdown_extensions package.


%prep
%setup -q -n pymdown-extensions-9.2
cd %{_builddir}/pymdown-extensions-9.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1644597782
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
